name: Update Docker Hub Description

on:
  push:
    branches:
      - main
      - master
    paths:
      - README.md

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD_ }}
        short-description: ${{ github.event.repository.description }}
#        repository: jipp13/torproxy
